//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFootDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodList
    {
        public int FoodID { get; set; }
        public string FoodName { get; set; }
        public string Pic { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> SalesVolume { get; set; }
    }
}
